import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { XMLParser } from 'fast-xml-parser';

interface NodePortSpec {
  name: string;
  type?: string;
}

interface NodeSpec {
  category: string;
  nodeDefName?: string;
  type?: string;
  inputs: NodePortSpec[];
  outputs: NodePortSpec[];
  parameters: NodePortSpec[];
}

type XmlRecord = Record<string, unknown>;

const parser = new XMLParser({
  ignoreAttributes: false,
  attributeNamePrefix: '',
  parseTagValue: false,
  trimValues: false,
});

const toArray = <T>(value: T | T[] | undefined): T[] => {
  if (value === undefined) {
    return [];
  }
  return Array.isArray(value) ? value : [value];
};

const asRecord = (value: unknown): XmlRecord => (value && typeof value === 'object' ? (value as XmlRecord) : {});

const parsePorts = (value: unknown): NodePortSpec[] =>
  toArray(value).map((entry) => {
    const attrs = asRecord(entry);
    return {
      name: String(attrs.name ?? ''),
      type: attrs.type ? String(attrs.type) : undefined,
    };
  });

const parseNodeDef = (entry: unknown): NodeSpec | undefined => {
  const attrs = asRecord(entry);
  const category = attrs.node ? String(attrs.node) : undefined;
  if (!category) {
    return undefined;
  }
  return {
    category,
    nodeDefName: attrs.name ? String(attrs.name) : undefined,
    type: attrs.type ? String(attrs.type) : undefined,
    inputs: parsePorts(attrs.input),
    outputs: parsePorts(attrs.output),
    parameters: parsePorts(attrs.parameter),
  };
};

const listMtlxFiles = async (directory: string): Promise<string[]> => {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listMtlxFiles(fullPath)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith('.mtlx')) {
      files.push(fullPath);
    }
  }
  return files;
};

const generateRegistry = async (librariesDir: string): Promise<NodeSpec[]> => {
  const files = await listMtlxFiles(librariesDir);
  const specsByName = new Map<string, NodeSpec>();

  for (const filePath of files) {
    const xml = await readFile(filePath, 'utf8');
    const parsed = parser.parse(xml) as XmlRecord;
    const root = asRecord(parsed.materialx);
    for (const nodeDef of toArray(root.nodedef)) {
      const spec = parseNodeDef(nodeDef);
      if (!spec) {
        continue;
      }
      const key = `${spec.category}::${spec.nodeDefName ?? ''}::${spec.type ?? ''}`;
      specsByName.set(key, spec);
    }
  }

  return [...specsByName.values()].toSorted((a, b) => {
    if (a.category !== b.category) {
      return a.category.localeCompare(b.category);
    }
    return (a.nodeDefName ?? '').localeCompare(b.nodeDefName ?? '');
  });
};

const toSource = (registry: NodeSpec[]): string => {
  const body = JSON.stringify(registry, null, 2);
  return `import type { MaterialXNodeSpec } from '../types.js';

// Generated by src/scripts/generate-node-registry.ts
export const generatedNodeRegistry: MaterialXNodeSpec[] = ${body};
`;
};

const main = async (): Promise<void> => {
  const packageRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..', '..');
  const librariesDir = process.env.MATERIALX_LIBRARIES_DIR
    ? path.resolve(process.env.MATERIALX_LIBRARIES_DIR)
    : path.resolve(packageRoot, '../../../MaterialX/libraries');
  const outputPath = path.resolve(packageRoot, 'src/generated/node-registry.generated.ts');

  const registry = await generateRegistry(librariesDir);
  await writeFile(outputPath, toSource(registry), 'utf8');

  process.stdout.write(`Generated ${registry.length} node specs from ${librariesDir}\n`);
};

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
  process.exit(1);
});
