export interface MaterialXSamplePack {
  id: string;
  label: string;
  description: string;
  directory: string;
  materialFile: string;
  assets: string[];
  infoFile: string;
}

export const materialXSamplePacks: MaterialXSamplePack[] = [
  {
    id: 'simple-standard-surface',
    label: 'Simple Standard Surface',
    description: 'Constant color and roughness baseline',
    directory: 'simple-standard-surface',
    materialFile: 'material.mtlx',
    assets: ['swatch.svg'],
    infoFile: 'info.txt',
  },
  {
    id: 'textured-standard-surface',
    label: 'Textured Standard Surface',
    description: 'Tiled textures for base color and roughness',
    directory: 'textured-standard-surface',
    materialFile: 'material.mtlx',
    assets: ['checker.svg', 'roughness.svg'],
    infoFile: 'info.txt',
  },
  {
    id: 'graph-standard-surface',
    label: 'Graph Mix with Texture',
    description: 'Nodegraph mix driven by a texture mask',
    directory: 'graph-standard-surface',
    materialFile: 'material.mtlx',
    assets: ['mask.svg'],
    infoFile: 'info.txt',
  },
  {
    id: 'open-pbr-default',
    label: 'OpenPBR Default',
    description: 'Upstream MaterialX open_pbr_default',
    directory: 'open_pbr_default',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'open-pbr-aluminum-brushed',
    label: 'OpenPBR Aluminum Brushed',
    description: 'Upstream MaterialX open_pbr_aluminum_brushed',
    directory: 'open_pbr_aluminum_brushed',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'open-pbr-carpaint',
    label: 'OpenPBR Carpaint',
    description: 'Upstream MaterialX open_pbr_carpaint',
    directory: 'open_pbr_carpaint',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'open-pbr-glass',
    label: 'OpenPBR Glass',
    description: 'Upstream MaterialX open_pbr_glass',
    directory: 'open_pbr_glass',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'open-pbr-honey',
    label: 'OpenPBR Honey',
    description: 'Upstream MaterialX open_pbr_honey',
    directory: 'open_pbr_honey',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'open-pbr-ketchup',
    label: 'OpenPBR Ketchup',
    description: 'Upstream MaterialX open_pbr_ketchup',
    directory: 'open_pbr_ketchup',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'open-pbr-lightbulb',
    label: 'OpenPBR Lightbulb',
    description: 'Upstream MaterialX open_pbr_lightbulb',
    directory: 'open_pbr_lightbulb',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'open-pbr-pearl',
    label: 'OpenPBR Pearl',
    description: 'Upstream MaterialX open_pbr_pearl',
    directory: 'open_pbr_pearl',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'open-pbr-soapbubble',
    label: 'OpenPBR Soapbubble',
    description: 'Upstream MaterialX open_pbr_soapbubble',
    directory: 'open_pbr_soapbubble',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'open-pbr-velvet',
    label: 'OpenPBR Velvet',
    description: 'Upstream MaterialX open_pbr_velvet',
    directory: 'open_pbr_velvet',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-brass-tiled',
    label: 'Standard Surface Brass Tiled',
    description: 'Upstream MaterialX standard_surface_brass_tiled',
    directory: 'standard_surface_brass_tiled',
    materialFile: 'material.mtlx',
    assets: ['brass_color.jpg', 'brass_roughness.jpg'],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-carpaint',
    label: 'Standard Surface Carpaint',
    description: 'Upstream MaterialX standard_surface_carpaint',
    directory: 'standard_surface_carpaint',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-chrome',
    label: 'Standard Surface Chrome',
    description: 'Upstream MaterialX standard_surface_chrome',
    directory: 'standard_surface_chrome',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-copper',
    label: 'Standard Surface Copper',
    description: 'Upstream MaterialX standard_surface_copper',
    directory: 'standard_surface_copper',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-default',
    label: 'Standard Surface Default',
    description: 'Upstream MaterialX standard_surface_default',
    directory: 'standard_surface_default',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-glass',
    label: 'Standard Surface Glass',
    description: 'Upstream MaterialX standard_surface_glass',
    directory: 'standard_surface_glass',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-glass-tinted',
    label: 'Standard Surface Glass Tinted',
    description: 'Upstream MaterialX standard_surface_glass_tinted',
    directory: 'standard_surface_glass_tinted',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-gold',
    label: 'Standard Surface Gold',
    description: 'Upstream MaterialX standard_surface_gold',
    directory: 'standard_surface_gold',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-greysphere',
    label: 'Standard Surface Greysphere',
    description: 'Upstream MaterialX standard_surface_greysphere',
    directory: 'standard_surface_greysphere',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-greysphere-calibration',
    label: 'Standard Surface Greysphere Calibration',
    description: 'Upstream MaterialX standard_surface_greysphere_calibration',
    directory: 'standard_surface_greysphere_calibration',
    materialFile: 'material.mtlx',
    assets: ['greysphere_calibration.png'],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-jade',
    label: 'Standard Surface Jade',
    description: 'Upstream MaterialX standard_surface_jade',
    directory: 'standard_surface_jade',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-marble-solid',
    label: 'Standard Surface Marble Solid',
    description: 'Upstream MaterialX standard_surface_marble_solid',
    directory: 'standard_surface_marble_solid',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-metal-brushed',
    label: 'Standard Surface Metal Brushed',
    description: 'Upstream MaterialX standard_surface_metal_brushed',
    directory: 'standard_surface_metal_brushed',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-plastic',
    label: 'Standard Surface Plastic',
    description: 'Upstream MaterialX standard_surface_plastic',
    directory: 'standard_surface_plastic',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-thin-film',
    label: 'Standard Surface Thin Film',
    description: 'Upstream MaterialX standard_surface_thin_film',
    directory: 'standard_surface_thin_film',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-velvet',
    label: 'Standard Surface Velvet',
    description: 'Upstream MaterialX standard_surface_velvet',
    directory: 'standard_surface_velvet',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'standard-surface-wood-tiled',
    label: 'Standard Surface Wood Tiled',
    description: 'Upstream MaterialX standard_surface_wood_tiled',
    directory: 'standard_surface_wood_tiled',
    materialFile: 'material.mtlx',
    assets: ['wood_color.jpg', 'wood_roughness.jpg'],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-color3-vec3-cm-test',
    label: 'Three.js Color3 Vec3 CM Test',
    description: 'Three.js MaterialX color3_vec3_cm_test',
    directory: 'color3_vec3_cm_test',
    materialFile: 'material.mtlx',
    assets: ['resources/Images/grid.png'],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-combined-test',
    label: 'Three.js Combined Test',
    description: 'Three.js MaterialX combined_test',
    directory: 'combined_test',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-conditional-if-float',
    label: 'Three.js Conditional If Float',
    description: 'Three.js MaterialX conditional_if_float',
    directory: 'conditional_if_float',
    materialFile: 'material.mtlx',
    assets: ['resources/Images/grid.png'],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-heightnormal',
    label: 'Three.js Heightnormal',
    description: 'Three.js MaterialX heightnormal',
    directory: 'heightnormal',
    materialFile: 'material.mtlx',
    assets: ['resources/Images/grid.png'],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-heighttonormal-normal-input',
    label: 'Three.js Heighttonormal Normal Input',
    description: 'Three.js MaterialX heighttonormal_normal_input',
    directory: 'heighttonormal_normal_input',
    materialFile: 'material.mtlx',
    assets: ['resources/Images/grid.png'],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-image-transform',
    label: 'Three.js Image Transform',
    description: 'Three.js MaterialX image_transform',
    directory: 'image_transform',
    materialFile: 'material.mtlx',
    assets: ['resources/Images/grid.png'],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-ior-test',
    label: 'Three.js IOR Test',
    description: 'Three.js MaterialX ior_test',
    directory: 'ior_test',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-opacity-only-test',
    label: 'Three.js Opacity Only Test',
    description: 'Three.js MaterialX opacity_only_test',
    directory: 'opacity_only_test',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-opacity-test',
    label: 'Three.js Opacity Test',
    description: 'Three.js MaterialX opacity_test',
    directory: 'opacity_test',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-rotate2d-test',
    label: 'Three.js Rotate2D Test',
    description: 'Three.js MaterialX rotate2d_test',
    directory: 'rotate2d_test',
    materialFile: 'material.mtlx',
    assets: ['resources/Images/grid.png'],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-rotate3d-test',
    label: 'Three.js Rotate3D Test',
    description: 'Three.js MaterialX rotate3d_test',
    directory: 'rotate3d_test',
    materialFile: 'material.mtlx',
    assets: ['resources/Images/grid.png'],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-roughness-test',
    label: 'Three.js Roughness Test',
    description: 'Three.js MaterialX roughness_test',
    directory: 'roughness_test',
    materialFile: 'material.mtlx',
    assets: ['resources/Images/grid.png'],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-sheen-test',
    label: 'Three.js Sheen Test',
    description: 'Three.js MaterialX sheen_test',
    directory: 'sheen_test',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-specular-test',
    label: 'Three.js Specular Test',
    description: 'Three.js MaterialX specular_test',
    directory: 'specular_test',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-texture-opacity-test',
    label: 'Three.js Texture Opacity Test',
    description: 'Three.js MaterialX texture_opacity_test',
    directory: 'texture_opacity_test',
    materialFile: 'material.mtlx',
    assets: ['resources/Images/grid.png'],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-thin-film-ior-clamp-test',
    label: 'Three.js Thin Film IOR Clamp Test',
    description: 'Three.js MaterialX thin_film_ior_clamp_test',
    directory: 'thin_film_ior_clamp_test',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-thin-film-rainbow-test',
    label: 'Three.js Thin Film Rainbow Test',
    description: 'Three.js MaterialX thin_film_rainbow_test',
    directory: 'thin_film_rainbow_test',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-transmission-only-test',
    label: 'Three.js Transmission Only Test',
    description: 'Three.js MaterialX transmission_only_test',
    directory: 'transmission_only_test',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-transmission-rough',
    label: 'Three.js Transmission Rough',
    description: 'Three.js MaterialX transmission_rough',
    directory: 'transmission_rough',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
  {
    id: 'threejs-transmission-test',
    label: 'Three.js Transmission Test',
    description: 'Three.js MaterialX transmission_test',
    directory: 'transmission_test',
    materialFile: 'material.mtlx',
    assets: [],
    infoFile: 'info.txt',
  },
];

export interface LoadedMaterialXSample {
  xml: string;
  assets: Record<string, string>;
  info: string;
}

export const loadMaterialXSamplePack = async (sample: MaterialXSamplePack): Promise<LoadedMaterialXSample> => {
  const root = `/examples/${sample.directory}`;
  const xmlResponse = await fetch(`${root}/${sample.materialFile}`);
  if (!xmlResponse.ok) {
    throw new Error(`Could not load sample material file: ${sample.materialFile}`);
  }
  const xml = await xmlResponse.text();

  const infoResponse = await fetch(`${root}/${sample.infoFile}`);
  const info = infoResponse.ok ? (await infoResponse.text()).trim() : sample.label;

  const assets: Record<string, string> = {};
  for (const asset of sample.assets) {
    assets[asset] = `${root}/${asset}`;
  }

  return { xml, assets, info };
};
